/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: leesokleng (https://sketchfab.com/leesokleng)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lightning-bolt-icons-48bb0ec8cdf445da91624c23bba28b5a
Title: Lightning Bolt Icons
*/

import { useGLTF } from '@react-three/drei';
import { useRef } from 'react';
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';

export function Bolt(props) {
  const { nodes, materials } = useGLTF('models/bolt.glb')

  const targetRef = useRef();

  useGSAP(() => {
    gsap.to(targetRef.current.position, {
      y: targetRef.current.position.y + 0.5,
      duration: 1.5,
      repeat: -1,
      yoyo: true,
    });
  });

  return (
    <group {...props} dispose={null} ref={targetRef} rotation={[Math.PI / 6, Math.PI, 0]}>
      <group scale={0.01}>
        <group position={[22.335, 2.429, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Extrude_Mat_0.geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rounding_1_Mat_0.geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cap_1_Mat_0.geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rounding_2_Mat_0.geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cap_2_Mat_0.geometry}
            material={materials.material}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/bolt.glb')