/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export function Plane(props) {
  const { nodes, materials } = useGLTF('/models/da40.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.049, 0, -0.8]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials['PLANE_TEXTURE.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.SILVER_NOSECONE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.Matériau}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.PROP_TEXTURE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.WHITE}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/da40.glb')