/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: mrarrt95 (https://sketchfab.com/mrarrt95)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mans-polo-8d8ffad8f85746f39b68f58629a8ce68
Title: Mans Polo
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei';

export function Polo(props) {
  const { nodes, materials } = useGLTF('/models/polo.glb')
  const monitortxt = useTexture('textures/polo-texture.png');
  const neutraltxt = useTexture('textures/cube.png');
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
        >
          <meshMatcapMaterial map={monitortxt} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
        >
          <meshMatcapMaterial map={monitortxt} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
        >
          <meshMatcapMaterial map={monitortxt} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/models/polo.glb')